name: ci
run-name: run tests
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -O --silent https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
      - run: tar xf zig-linux-x86_64-0.13.0.tar.xz
      - run: zig-linux-x86_64-0.13.0/zig build
